[head]
pi ansible_user=nlunberry

[compute]
node01 ansible_user=node01
node02 ansible_user=node02
node03 ansible_user=node03

[monitoring]
pi ansible_user=nlunberry

[cluster:children]
head
compute
monitoring
